[toolchain]
anchor_version = "0.29.0" 

[features]
seeds = false
skip-lint = false

[programs.localnet]
orca_tst = "9kUZv9JjkuAsTEmauboSaCzBH5cfFjThyWecCeYXFQ5h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests-env/test-wallet.json"

[test]
startup_wait = 1000