[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
moai = "2Svk2fb1YwpjKrxktUabBsYYm49HiXyxHpAAAK5g6K9t"
orca_test = "9kUZv9JjkuAsTEmauboSaCzBH5cfFjThyWecCeYXFQ5h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet-archive.allthatnode.com/Ez7eqjgszCRYxMTozvryy4B5Y8qvR5Q7/"
# cluster = "Localnet"
wallet = "./tests-env/test-wallet.json"

[test]
startup_wait = 4000
shutdown_wait = 2000
upgradeable = false
