[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
orca_tst = "Auk5McF2qPTR2f1CXxvg8MGPSiPGusULqE5k2sLjJy7g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests/test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --trace-warnings"
