[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
fairsale = "3SmnwsonVtHkHbApWRJkL4LPd72c66QrWFEX5EFdBppj"
moai = "2Svk2fb1YwpjKrxktUabBsYYm49HiXyxHpAAAK5g6K9t"
orca_test = "9kUZv9JjkuAsTEmauboSaCzBH5cfFjThyWecCeYXFQ5h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests-env/test-wallet.json"

[test]
startup_wait = 1000
shutdown_wait = 2000
upgradeable = false
